# Generated by Django 4.2.3 on 2023-08-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_name', models.CharField(max_length=100)),
                ('tea_id', models.IntegerField(verbose_name='0-9')),
            ],
        ),
    ]
