# Generated by Django 4.2.4 on 2023-08-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teachers',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tea_id',
            new_name='t_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tea_name',
            new_name='t_name',
        ),
    ]
